NewsApp/Areas/AdminAreas/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsApp.Models;

namespace NewsApp.Areas.AdminAreas.Controllers
{
    public class ThongKeController : Controller
    {
        NewsDBEntities db = new NewsDBEntities();
        // GET: AdminAreas/ThongKe
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.TinTuc = db.TinTucs.ToList();
            ViewBag.TinTuc.Reverse();

            var maxLuotXemTinTuc = db.TinTucs.FirstOrDefault();

            foreach (var item in ViewBag.TinTuc)
            {
                if(item.LuotXem > maxLuotXemTinTuc.LuotXem)
                {
                    maxLuotXemTinTuc = item; 
                }
            }
            ViewBag.MaxLuotXem = maxLuotXemTinTuc;



            var maxBinhLuanTinTuc = db.TinTucs.FirstOrDefault();
            foreach (var item in ViewBag.TinTuc)
            {
                if (item.GetBinhLuanCount() > maxBinhLuanTinTuc.GetBinhLuanCount())
                {
                    maxBinhLuanTinTuc = item;
                }
            }
            ViewBag.MaxBinhLuan = maxBinhLuanTinTuc;
            ViewBag.ThongBao = "";

            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection dayForm)
        {
            var maxLuotXemTinTuc = db.TinTucs.FirstOrDefault();
            var maxBinhLuanTinTuc = db.TinTucs.FirstOrDefault();

            

            DateTime parseDateTime;
            if (DateTime.TryParse(dayForm["dayStart"].ToString(), out parseDateTime) && DateTime.TryParse(dayForm["dayEnd"].ToString(), out parseDateTime))
            {
                var dayStart = DateTime.Parse(dayForm["dayStart"]);

                var dayEnd = DateTime.Parse(dayForm["dayEnd"]);
                ViewBag.TinTuc = db.TinTucs.Where(n => n.NgayDang >= dayStart && n.NgayDang <= dayEnd).ToList();
                ViewBag.TinTuc.Reverse();

                maxLuotXemTinTuc = db.TinTucs.FirstOrDefault(n => n.NgayDang >= dayStart && n.NgayDang <= dayEnd);

                foreach (var item in ViewBag.TinTuc)
                {
                    if (item.LuotXem > maxLuotXemTinTuc.LuotXem)
                    {
                        maxLuotXemTinTuc = item;
                    }
                }
                ViewBag.MaxLuotXem = maxLuotXemTinTuc;



                maxBinhLuanTinTuc = db.TinTucs.FirstOrDefault(n => n.NgayDang >= dayStart && n.NgayDang <= dayEnd);
                foreach (var item in ViewBag.TinTuc)
                {
                    if (item.GetBinhLuanCount() > maxBinhLuanTinTuc.GetBinhLuanCount())
                    {
                        maxBinhLuanTinTuc = item;
                    }
                }
                ViewBag.MaxBinhLuan = maxBinhLuanTinTuc;
            }
            else
            {
                ViewBag.TinTuc = db.TinTucs.ToList();
                ViewBag.TinTuc.Reverse();

                 maxLuotXemTinTuc = db.TinTucs.FirstOrDefault();

                foreach (var item in ViewBag.TinTuc)
                {
                    if (item.LuotXem > maxLuotXemTinTuc.LuotXem)
                    {
                        maxLuotXemTinTuc = item;
                    }
                }
                ViewBag.MaxLuotXem = maxLuotXemTinTuc;



                 maxBinhLuanTinTuc = db.TinTucs.FirstOrDefault();
                foreach (var item in ViewBag.TinTuc)
                {
                    if (item.GetBinhLuanCount() > maxBinhLuanTinTuc.GetBinhLuanCount())
                    {
                        maxBinhLuanTinTuc = item;
                    }
                }
                ViewBag.MaxBinhLuan = maxBinhLuanTinTuc;
                ViewBag.ThongBao = "Xin hãy nhập đủ ngày tháng năm";
            }
            return View();
        }
    }
}

NewsApp/Areas/AdminAreas/Views/ThongKe/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .table-statistic {
        border: 1px solid gray;
        margin: 30px 10px;
        border-radius: 30px;
    }

    .statistic {
        border: 1px solid gray;
        color: gray;
        border-radius: 30px;
        padding: 10px;
        margin: 10px;
    }
</style>
<h2> Thống kê bài viết</h2>
<div class="row">
    <div class="col-lg-4 statistic">
        <h3>Lượt xem nhiều nhất : </h3>
        <div><a href="#">@ViewBag.MaxLuotXem.TieuDe</a></div>
    </div>

    <div class="col-lg-4 statistic">
        <h3>Bình luận nhiều nhất : </h3>
        <div><a href="#">@ViewBag.MaxBinhLuan.TieuDe</a> </div>
    </div>
</div>
<hr />

<div>
    @using (Html.BeginForm("Index", "ThongKe", FormMethod.Post))
    {
       <div class="row">
           <div class="col-lg-3 statistic">
               <span>Từ ngày</span>
               <input name="dayStart" type="date" />
           </div>

           <div class="col-lg-3 statistic">
               <span>Đến ngày</span>
               <input name="dayEnd" type="date" />
           </div>
           <div class="col-lg-3 statistic" style="border:none">
               <button type="submit" class="btn btn-success">Thống kê</button>
           </div>
           
       </div>
       <span style="color:red">@ViewBag.ThongBao</span>
    }
    </div>

<table class="table table-statistic">
    <tr>
        <th>
            Tiêu đề
        </th>
        <th>
            Lượt xem
        </th>

        <th>
            Ngày đăng
        </th>

        <th>
            Nguồn
        </th>

        <th></th>
    </tr>

    @foreach (var item in ViewBag.TinTuc)
    {
        <tr>
            <td>
                @item.TieuDe
            </td>
            <td>
                @item.LuotXem
            </td>


            <td>
                @item.NgayDang.ToString("dd/MM/yyyy")

            </td>

            <td>
                @item.Nguon
            </td>


        </tr>
    }

</table>