NewsApp/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinTuc()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.XemSaus = new HashSet<XemSau>();
        }
    
        public int IDTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public string Nguon { get; set; }
        public int IDDanhMuc { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XemSau> XemSaus { get; set; }

        public int GetBinhLuanCount()
        {
            int count = this.BinhLuans.Count;
            return count;
        }
    }
}

NewsApp/Areas/AdminAreas/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewsApp.Models;
using System.IO;

namespace NewsApp.Areas.AdminAreas.Controllers
{
    public class TinTucsController : Controller
    {
        private NewsDBEntities db = new NewsDBEntities();

        // GET: AdminAreas/TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.Include(t => t.DanhMuc);
            return View(tinTucs.ToList());
        }

        // GET: AdminAreas/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: AdminAreas/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.IDDanhMuc = new SelectList(db.DanhMucs, "IDDanhMuc", "TenDanhMuc");
            return View();
        }

        // POST: AdminAreas/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TinTuc tinTuc, HttpPostedFileBase HinhAnh)
        {
            if (ModelState.IsValid)
            {
                if (HinhAnh != null)
                {
                    var fileName = Path.GetFileName(HinhAnh.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    tinTuc.HinhAnh = fileName;
                    HinhAnh.SaveAs(path);
                }

                tinTuc.NgayDang = DateTime.Now;
                tinTuc.NoiDung += ".";
                tinTuc.LuotXem = 0;
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDDanhMuc = new SelectList(db.DanhMucs, "IDDanhMuc", "TenDanhMuc", tinTuc.IDDanhMuc);
            return View(tinTuc);
        }

        // GET: AdminAreas/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDDanhMuc = new SelectList(db.DanhMucs, "IDDanhMuc", "TenDanhMuc", tinTuc.IDDanhMuc);
            return View(tinTuc);
        }

        // POST: AdminAreas/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TinTuc tinTuc, HttpPostedFileBase HinhAnhTin)
        {
            if (ModelState.IsValid)
            {
                if (HinhAnhTin != null)
                {
                    var fileName = Path.GetFileName(HinhAnhTin.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    tinTuc.HinhAnh = fileName.ToString();
                    HinhAnhTin.SaveAs(path);
                }


                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDDanhMuc = new SelectList(db.DanhMucs, "IDDanhMuc", "TenDanhMuc", tinTuc.IDDanhMuc);
            return View(tinTuc);
        }

        // GET: AdminAreas/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: AdminAreas/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            var lstCommentTinTuc = db.BinhLuans.Where(c => c.IDTinTuc == id).ToList();
            var lstLastSeenTinTuc = db.XemSaus.Where(c => c.IDTinTuc == id).ToList();
            foreach (var item in lstCommentTinTuc)
            {
                db.BinhLuans.Remove(item);
            }
            foreach (var item in lstLastSeenTinTuc)
            {
                db.XemSaus.Remove(item);
            }
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsApp/Areas/AdminAreas/Views/TinTucs/Create.cshtml
@model NewsApp.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Thêm tin mới</h2>

@using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Tiêu đề
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })*@
                <textarea name="TieuDe" style="width:100%; font-weight:bold; font-size:20px" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Mô tả
            <div class="col-md-10">
                <textarea name="MoTa" style="width:100%; font-weight:bold; font-size:15px" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Hình ảnh
            <div class="col-md-10">
                <img src="~/Images/" style="width:30%" id="img_book_upload" alt="">
                <input accept="~Content/Images/*" type="file" id="img_book_upload_btn" name="HinhAnh">
                <script>
                    img_book_upload_btn.onchange = evt => {
                        const [file] = img_book_upload_btn.files
                        if (file) {
                            img_book_upload.src = URL.createObjectURL(file)
                        }
                    }
                </script>
            </div>
        </div>

        <div class="form-group">
            Nội dung
            <div class="col-md-10">
                <textarea name="NoiDung" style="width:100%; height: 200px" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            Hiển thị nổi bật
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NoiBat, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NoiBat, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            Nguồn
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nguon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nguon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDDanhMuc, "IDDanhMuc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm tin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

NewsApp/Areas/AdminAreas/Views/TinTucs/Delete.cshtml
@model NewsApp.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Xóa tin tức</h2>

<h3>Bạn có chắc chắn muốn xóa tin tức này không ? </h3>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="hidden" name="id" value="@Model.IDTinTuc"/>
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

NewsApp/Areas/AdminAreas/Views/TinTucs/Details.cshtml
@model NewsApp.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiBat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiBat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nguon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nguon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDTinTuc }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NewsApp/Areas/AdminAreas/Views/TinTucs/Edit.cshtml
@model NewsApp.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Chỉnh sửa tin tức</h2>

@using (Html.BeginForm("Edit", "TinTucs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>TinTuc</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDTinTuc)

    <div class="form-group">
        Tiêu đề
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })*@
            <textarea name="TieuDe" style="width:100%; font-weight:bold; font-size:20px" class="form-control">@Model.TieuDe</textarea>
            @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Mô tả
        <div class="col-md-10">
            <textarea name="MoTa" style="width:100%; font-weight:bold; font-size:15px" class="form-control">@Model.MoTa</textarea>
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        Hình ảnh
        <div class="col-md-10">
            <img src="~/Images/@Model.HinhAnh" style="width:30%" id="img_book_upload" alt="">
            <input accept="~Content/Images/*" type="file" id="img_book_upload_btn" name="HinhAnhTin" value="@Model.HinhAnh">
            <input type="hidden" name="HinhAnh" value="@Model.HinhAnh" id="img_name_file"/>
            <script>
                img_book_upload_btn.onchange = evt => {
                    const [file] = img_book_upload_btn.files
                    if (file) {
                        img_book_upload.src = URL.createObjectURL(file)
                        var imgValue = document.getElementById("img_book_upload_btn");
                        var imgName = document.getElementById("img_name_file");
                        imgName.value = imgValue.files[0].name
                    }
                }
                
            </script>
        </div>
    </div>

    <div class="form-group">
        Nội dung
        <div class="col-md-10">
            <textarea name="NoiDung" style="width:100%; height: 200px" class="form-control">@Model.NoiDung</textarea>
            @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
        </div>
    </div>



    <input type="hidden" name="NgayDang" value="@Model.NgayDang" />

    <div class="form-group">
        Hiển thị nổi bật
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.NoiBat)
                @Html.ValidationMessageFor(model => model.NoiBat, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        Nguồn
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nguon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nguon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Danh mục
        <div class="col-md-10">
            @Html.DropDownList("IDDanhMuc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDDanhMuc, "", new { @class = "text-danger" })
        </div>
        <input name="LuotXem" value="@Model.LuotXem" type="hidden" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

NewsApp/Areas/AdminAreas/Views/TinTucs/Index.cshtml
@model IEnumerable<NewsApp.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Quản lý tin tức</h2>

<p>
    @Html.ActionLink("Thêm tin mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tiêu đề
        </th>
        <th>
            Mô tả
        </th>
        
        <th>
            Ngày đăng
        </th>
        
        <th>
            Nguồn
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TieuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        
       
        <td>
            @Html.DisplayFor(modelItem => item.NgayDang)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Nguon)
        </td>
        
        <td>
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id=item.IDTinTuc }) |
            @*@Html.ActionLink("Xem chi tiết", "Edit", new { id=item.IDTinTuc }) |*@ 
            @Html.ActionLink("Xóa", "Delete", new { id=item.IDTinTuc })
        </td>
    </tr>
}

</table>