NewsApp/Models/QuangCao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int IDQuangCao { get; set; }
        public string Link { get; set; }
        public string HinhAnhQuangCao { get; set; }
    }
}

NewsApp/Areas/AdminAreas/Controllers/QuangCaosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewsApp.Models;

namespace NewsApp.Areas.AdminAreas.Controllers
{
    public class QuangCaosController : Controller
    {
        private NewsDBEntities db = new NewsDBEntities();

        // GET: AdminAreas/QuangCaos
        public ActionResult Index()
        {
            return View(db.QuangCaos.ToList());
        }

        // GET: AdminAreas/QuangCaos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuangCao quangCao = db.QuangCaos.Find(id);
            if (quangCao == null)
            {
                return HttpNotFound();
            }
            return View(quangCao);
        }

        // GET: AdminAreas/QuangCaos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminAreas/QuangCaos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDQuangCao,Link,HinhAnhQuangCao")] QuangCao quangCao)
        {
            if (ModelState.IsValid)
            {
                db.QuangCaos.Add(quangCao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quangCao);
        }

        // GET: AdminAreas/QuangCaos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuangCao quangCao = db.QuangCaos.Find(id);
            if (quangCao == null)
            {
                return HttpNotFound();
            }
            return View(quangCao);
        }

        // POST: AdminAreas/QuangCaos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( QuangCao quangCao, HttpPostedFileBase HinhAnh)
        {
            if (ModelState.IsValid)
            {
                if (HinhAnh != null)
                {
                    var fileName = Path.GetFileName(HinhAnh.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    quangCao.HinhAnhQuangCao = fileName;
                    HinhAnh.SaveAs(path);
                }
                db.Entry(quangCao).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quangCao);
        }

        // GET: AdminAreas/QuangCaos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuangCao quangCao = db.QuangCaos.Find(id);
            if (quangCao == null)
            {
                return HttpNotFound();
            }
            return View(quangCao);
        }

        // POST: AdminAreas/QuangCaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuangCao quangCao = db.QuangCaos.Find(id);
            db.QuangCaos.Remove(quangCao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewsApp/Areas/AdminAreas/Views/QuangCaos/Create.cshtml
@model NewsApp.Models.QuangCao

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuangCao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDQuangCao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDQuangCao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDQuangCao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnhQuangCao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnhQuangCao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnhQuangCao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NewsApp/Areas/AdminAreas/Views/QuangCaos/Delete.cshtml
@model NewsApp.Models.QuangCao

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuangCao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhQuangCao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhQuangCao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NewsApp/Areas/AdminAreas/Views/QuangCaos/Details.cshtml
@model NewsApp.Models.QuangCao

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>QuangCao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhQuangCao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhQuangCao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDQuangCao }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NewsApp/Areas/AdminAreas/Views/QuangCaos/Edit.cshtml
@model NewsApp.Models.QuangCao

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "QuangCaos", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuangCao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDQuangCao)

        <div class="form-group">
            @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnhQuangCao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Hình ảnh
                <div class="col-md-10">
                    <img src="~/Images/@Model.HinhAnhQuangCao" style="width:30%" id="img_book_upload" alt="">
                    <input accept="~Content/Images/*" type="file" id="img_book_upload_btn" name="HinhAnh">
                    <script>
                        img_book_upload_btn.onchange = evt => {
                            const [file] = img_book_upload_btn.files
                            if (file) {
                                img_book_upload.src = URL.createObjectURL(file)
                            }
                        }
                    </script>
                </div>

                @Html.ValidationMessageFor(model => model.HinhAnhQuangCao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NewsApp/Areas/AdminAreas/Views/QuangCaos/Index.cshtml
@model IEnumerable<NewsApp.Models.QuangCao>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminAreas/Views/Shared/_AdminLayout.cshtml";
}

<h2>Quản lý quảng cáo</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Link)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnhQuangCao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Link)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HinhAnhQuangCao)
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", new { id=item.IDQuangCao }) |
          
            
        </td>
    </tr>
}

</table>